---

##############################################################################
# mit-venv v2025-01-29
##############################################################################

- name: Set target to /opt/zfs-autobackup
  ansible.builtin.set_fact:
    target: /opt/zfs-autobackup

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: "{{ target }}/"
    mode: "644"

- name: Install python3-venv
  ansible.builtin.apt:
    pkg: python3-venv
  when: ansible_os_family == "Debian"

# Either 39 or 311 (py39 py311)
- name: Get python prefix # noqa: risky-shell-pipe
  ansible.builtin.shell: pkg info|egrep -o "^python[0-9]{2,3}-"|egrep -o "[0-9]+"
  register: python_prefix
  changed_when: false
  when: ansible_os_family == "FreeBSD"

- name: Install py{{ python_prefix.stdout }}-packaging # noqa: name[template]
  ansible.builtin.package:
    name: py{{ python_prefix.stdout }}-packaging
  when: ansible_os_family == "FreeBSD"

- name: Install pip in venv
  ansible.builtin.pip:
    name: pip
    virtualenv: "{{ target }}/.venv"
    virtualenv_command: python3 -m venv

- name: Updated python dependencies (requirements.txt)
  ansible.builtin.pip:
    virtualenv_command: python3 -m venv
    requirements: "{{ target }}/requirements.txt"
    virtualenv: "{{ target }}/.venv"
  environment: "{{ proxy_env }}"
