---
# Common tasks for all Linux machines.

- name: "Logrotate: Enable compress"
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.d/0-local
    create: true
    regexp: compress$
    line: compress

- name: "Logrotate: Enable dateext"
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.d/0-local
    create: true
    regexp: dateext$
    line: dateext

- name: Disable IPv6
  ansible.builtin.template:
    src: local-disable-ipv6.conf
    dest: /etc/sysctl.d/
  when: "'ipv6_disabled' in group_names"

- name: Setup ssh with sftp and chroot
  ansible.builtin.copy:
    src: local-sftp-chroot.conf
    dest: /etc/ssh/sshd_config.d/
  notify: Reload sshd
  when: "'sshd_sftp_chroot' in group_names"
