---
# Regular zfs snapshots [MIT-21715]

- name: Create zfs tag for periodical snapshots
  ansible.builtin.command:
    cmd: "zfs set autobackup:localsnap=true {{ zfs_autobackup_storage_pool }}"
  changed_when: false

- name: Set excludes for zfs-autobackup
  ansible.builtin.command:
    cmd: "zfs set autobackup:localsnap=false {{ item }}"
  changed_when: false
  with_items:
    - "{{ mit_basic_zfs_snapshot_excludes }}"
  when: mit_basic_zfs_snapshot_excludes is defined

- name: Install zfs-autobackup cronjob
  ansible.builtin.cron:
    user: root
    name: Regular zfs snapshots [MIT-21715]
    special_time: hourly
    job: "{{ zfs_autobackup_binary }} localsnap --keep-source 1h1d,1d1w"
