---
# Handlers

- name: Newaliases
  # 2023-11-16: postfix: /usr/bin/newaliases, sendmail: /usr/sbin/newaliases
  ansible.builtin.command: newaliases
  changed_when: true

- name: Update-ca-certificates
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  changed_when: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart ntpd
  ansible.builtin.service:
    name: ntpd
    state: restarted

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Sshd configtest
  ansible.builtin.command: sshd -t
  changed_when: true
  register: sshd_configtest
  listen:
    - Reload sshd
    - Restart sshd

- name: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
  when: sshd_configtest.rc == 0
  listen: Reload sshd

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: sshd_configtest.rc == 0
  listen: Restart sshd

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

# https://github.com/tykling/ansible-roles/blob/master/handlers/handlers/main.yml
- name: Rename sequential logs
  ansible.builtin.shell: |
    INCLUDEPATHS=$(cat /etc/newsyslog.conf | grep "^<include>" | cut -d " " -f 2)
    for LOGPATH in $(cat /etc/newsyslog.conf $INCLUDEPATHS | grep -Ev "^(#|$|<include>)" | awk "{print \$1}" | sed -e 's,/[^/]*$,,' | sort -u); do
        for EXT in bz2 xz; do
            for FILE in $(ls -1 ${LOGPATH}/*.${EXT}); do
                MTIME=$(stat -f %Sm -t "%Y%m%dT%H%M%S" ${FILE})
                NEWNAME=$(echo $(basename ${FILE}) | sed -E "s/(.+)\.[0-9]+\.${EXT}/\1.${MTIME}.${EXT}/")
                mv ${FILE} $(dirname ${FILE})/${NEWNAME}
            done
        done
    done
