---
# Handlers

- name: newaliases
  # 2023-11-16: postfix: /usr/bin/newaliases, sendmail: /usr/sbin/newaliases
  command: newaliases

- name: update-ca-certificates
  command: /usr/sbin/update-ca-certificates

- name: Update apt cache
  apt:
    update_cache: yes

- name: Restart chrony
  service:
    name: chrony
    state: restarted

- name: Restart ntpd
  service:
    name: ntpd
    state: restarted

- name: sshd configtest
  command: sshd -t
  register: sshd_configtest
  listen:
    - Reload sshd
    - Restart sshd

- name: Reload sshd
  service:
    name: sshd
    state: reloaded
  when: sshd_configtest.rc == 0
  listen: Reload sshd

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: sshd_configtest.rc == 0
  listen: Restart sshd

# https://github.com/tykling/ansible-roles/blob/master/handlers/handlers/main.yml
- name: "rename sequential logs"
  shell: |
    INCLUDEPATHS=$(cat /etc/newsyslog.conf | grep "^<include>" | cut -d " " -f 2)
    for LOGPATH in $(cat /etc/newsyslog.conf $INCLUDEPATHS | grep -Ev "^(#|$|<include>)" | awk "{print \$1}" | sed -e 's,/[^/]*$,,' | sort -u); do
        for EXT in bz2 xz; do
            for FILE in $(ls -1 ${LOGPATH}/*.${EXT}); do
                MTIME=$(stat -f %Sm -t "%Y%m%dT%H%M%S" ${FILE})
                NEWNAME=$(echo $(basename ${FILE}) | sed -E "s/(.+)\.[0-9]+\.${EXT}/\1.${MTIME}.${EXT}/")
                mv ${FILE} $(dirname ${FILE})/${NEWNAME}
            done
        done
    done

