#!/usr/bin/env bash
#
# Distributed via ansible - mit.basic

[ -d /.mit-disk-info ] || mkdir /.mit-disk-info

if [ -f /sbin/fdisk ]; then
    FDISK=fdisk
else
    FDISK=gdisk
fi

for disk in $(find /dev/ \( -name "sd?" -o -name "vd?" \) -printf '%f\n'); do
    ${FDISK} -l /dev/${disk} > /.mit-disk-info/${disk}.${FDISK}
done

